# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-21 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella_system', '0002_auto_20160613_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_flg',
        ),
        migrations.AddField(
            model_name='room',
            name='seats',
            field=models.IntegerField(default=0),
        ),
    ]
