# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-24 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella_system', '0003_auto_20160621_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='time_zone_id',
            new_name='time',
        ),
    ]
