# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-12 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella_system', '0005_auto_20160624_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
