# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-12 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella_system', '0006_user_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='user_ids',
        ),
    ]
