# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-22 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella_system', '0007_auto_20160712_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('holiday_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
